stages:
  - build
  - test

build:binary:
  image: golang:latest
  stage: build
  script:
    - make
  artifacts:
    paths:
      - bin/rait

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Coverage-Fuzzing.gitlab-ci.yml
