stages:
  - build

build:binary:
  image: golang:latest
  stage: build
  script:
    - go build -o bin/rait cmd/rait/rait.go
  artifacts:
    paths:
      - bin/rait

include:
  - template: Dependency-Scanning.gitlab-ci.yml
