language: go

go:
  - "1.14.x"

deploy:
  - provider: script
    script: make upload-master
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: make upload-tag
    skip_cleanup: true
    on:
      tags: true

