package rait

import (
	"bytes"
	"io/ioutil"
	"strconv"
	"text/template"
)

const BabeldConfigTemplate = `# Generated by rait up
export-table 254
default type tunnel link-quality true max-rtt-penalty 1024 rtt-max 1024
default split-horizon true hello-interval 20 rxcost 32
{{$prefix := .IFPrefix}}
interface {{$prefix}}local type wired
{{range .IFSuffix}}interface {{$prefix}}{{.}}
{{end}}
redistribute local deny
`

func GenerateBabeldConfig(IFPrefix string, n int, filepath string) error {
	var IFSuffix []string
	for i := 0; i < n; i++ {
		IFSuffix = append(IFSuffix, strconv.Itoa(i))
	}
	tmpl, err := template.New("babeld.conf").Parse(BabeldConfigTemplate)
	if err != nil {
		return err
	}
	var conf bytes.Buffer
	err = tmpl.Execute(&conf, struct {
		IFPrefix string
		IFSuffix []string
	}{
		IFPrefix: IFPrefix,
		IFSuffix: IFSuffix,
	})
	if err != nil {
		return err
	}
	err = CreateParentDirIfNotExist(filepath)
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(filepath, conf.Bytes(), 0644)
	if err != nil {
		return err
	}
	return nil
}
